<?php 
/**
 * Equity Framework
 *
 * WARNING: This file is part of the core Equity Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Equity\IDX
 * @author  Agent Evolution
 * @license GPL-2.0+
 * @link    http://equityframework.com
 */

/**
 * Creates a widget that outputs the idx lead login form
 *
 * @package IDX Integration
 * @subpackage Widgets
 * @see Equity_Idx_Api
 */
class Equity_Lead_Signup_Widget extends WP_Widget {

	public $_idx;

	/**
	 * Register widget with WordPress.
	 */
	public function __construct() {

		$this->_idx = new Equity_Idx_Api;

		parent::__construct(
	 		'equity_lead_signup',   // Base ID
			__( 'Equity - IDX Lead Sign Up', 'equity' ), // Name
			array(
				'description' => __( 'Lead sign up form', 'equity' ),
				'classname'   => 'equity-idx-signup-widget'
			)
		);
	}

	/**
	 * Front-end display of widget.
	 *
	 * @see WP_Widget::widget()
	 *
	 * @param array $args Widget arguments.
	 * @param array $instance Saved values from database.
	 */
	public function widget( $args, $instance ) {
		extract( $args );
		$title = $instance['title'];
		$custom_text = $instance['custom_text'];

		echo $before_widget;

		if ( ! empty( $title ) ) {
			echo $before_title . $title . $after_title;
		}

		if ( !empty($custom_text) ) {
			echo '<p>', $custom_text, '</p>';
		}

		?>
		<form action="<?php echo $this->_idx->subdomain_url(); ?>ajax/usersignup.php" method="post" target="" name="LeadSignup">
			<input type="hidden" name="action" value="addLead">
			<input type="hidden" name="signupWidget" value="true">
			<input type="hidden" name="contactType" value="direct">

			<label id="bb-IDX-widgetfirstName-label" class="ie-only" for="IDX-widgetfirstName"><?php _e( 'First Name:','equity' ); ?></label>
			<input id="bb-IDX-widgetfirstName" type="text" name="firstName" placeholder="First Name">

			<label id="bb-IDX-widgetlastName-label" class="ie-only" for="IDX-widgetlastName"><?php _e( 'Last Name:','equity' ); ?></label>
			<input id="bb-IDX-widgetlastName" type="text" name="lastName" placeholder="Last Name">

			<label id="bb-IDX-widgetemail-label" class="ie-only" for="IDX-widgetemail"><?php _e( 'Email:','equity' ); ?></label>
			<input id="bb-IDX-widgetemail" type="text" name="email" placeholder="Email">

			<?php if ($instance['phone_number'] == true) {
				echo '
				<label id="bb-IDX-widgetphone-label" class="ie-only" for="IDX-widgetphone">' . __( 'Phone:','equity' ) . '</label>
				<input id="bb-IDX-widgetphone" type="text" name="phone" placeholder="Phone">';
			} ?>

			<input id="bb-IDX-widgetsubmit" type="submit" name="submit" value="Sign Up!">
		</form>
		<?php

		echo $after_widget;
	}

	/**
	 * Sanitize widget form values as they are saved.
	 *
	 * @see WP_Widget::update()
	 *
	 * @param array $new_instance Values just sent to be saved.
	 * @param array $old_instance Previously saved values from database.
	 * @return array Updated safe values to be saved.
	 */
	public function update( $new_instance, $old_instance ) {
		$instance = array();
		$instance['title']       = strip_tags( $new_instance['title'] );
		$instance['custom_text'] = htmlentities( $new_instance['custom_text'] );
		$instance['phone_number'] = $new_instance['phone_number'];

		return $instance;
	}

	/**
	 * Back-end widget form.
	 *
	 * @see WP_Widget::form()
	 * @param array $instance Previously saved values from database.
	 */
	public function form( $instance ) {

		$_idx = $this->_idx;

		$defaults = array(
			'title'          => __('Lead Sign Up', 'equity'),
			'custom_text'    => '',
			'phone_number'    => false
		);

		$instance = wp_parse_args( (array) $instance, $defaults );

		?>
		<p>
			<label for="<?php echo $this->get_field_id( 'title' ); ?>"><?php _e( 'Title:' ); ?></label>
			<input class="widefat" id="<?php echo $this->get_field_id( 'title' ); ?>" name="<?php echo $this->get_field_name( 'title' ); ?>" type="text" value="<?php esc_attr_e( $instance['title'] ); ?>" />
		</p>
		<p>
			<label for="<?php echo $this->get_field_id( 'custom_text') ?>"><?php _e( 'Custom Text', 'equity' ); ?></label>
			<textarea class="widefat" id="<?php echo $this->get_field_id( 'custom_text' ); ?>" name="<?php echo $this->get_field_name( 'custom_text' ); ?>" value="<?php esc_attr_e( $instance['custom_text'] ); ?>" rows="5"><?php esc_attr_e( $instance['custom_text'] ); ?></textarea>
		</p>
		<p>
			<label for="<?php echo $this->get_field_id( 'phone_number' ); ?>"><?php _e( 'Show phone number field?', 'equity' ); ?></label>
			<input type="checkbox" id="<?php echo $this->get_field_id( 'phone_number' ); ?>" name="<?php echo $this->get_field_name( 'phone_number' ) ?>" value="1" <?php checked( $instance['phone_number'], true ); ?>>
		</p>
		<?php
	}
}